name: Sebabe

description: My journey in tech, programming & innovation

avatar: https://avatars.githubusercontent.com/u/165440637?s=400&u=e10aefe7bdb1c4aa66a8b054c15d4efaf7ced03a&v=4

header_pages:
  - about.md
  - projects.md

footer-links:
  github: sebabe
  twitter:
  email:
  linkedin:

url: "https://sebabe.github.io"

baseurl: "/sebabe-git-bloq"

permalink: /:title/

gems:
  - jekyll-sitemap
  - jekyll-feed
